### ISSUE TITLE
Where is the config file after build?

### ISSUE THREAD

**Issue by hellomotow** [coinfoundry/miningcore#196]
I can't find the config.json file which should be made after building.

```console
root@ubuntu:~/miningcore# find /root/miningcore -name "*.json"
/root/miningcore/src/MiningCore/bin/Release/netcoreapp2.0/MiningCore.runtimeconfig.json
/root/miningcore/src/MiningCore/bin/Release/netcoreapp2.0/MiningCore.runtimeconfig.dev.json
/root/miningcore/src/MiningCore/bin/Release/netcoreapp2.0/MiningCore.deps.json
/root/miningcore/src/MiningCore/Properties/launchSettings.json
/root/miningcore/src/MiningCore/obj/project.assets.json
/root/miningcore/src/MiningCore.Tests/xunit.runner.json
/root/miningcore/build/MiningCore.runtimeconfig.json
/root/miningcore/build/MiningCore.deps.json
/root/miningcore/examples/dash_pool.json
/root/miningcore/examples/monero_pool.json
/root/miningcore/examples/ethereum_pool.json
/root/miningcore/examples/litecoin_pool.json
/root/miningcore/examples/straks_pool.json
/root/miningcore/examples/dash_pool_no_polling.json
/root/miningcore/examples/litecoin_dash_pool.json
/root/miningcore/examples/digibyte_sha256_pool.json
/root/miningcore/examples/zcash_pool.json
/root/miningcore/examples/digibyte_scrypt_pool.json
```

**Comment by saltyminer** [comment]
Assuming you are using windows, take a look at the readme [here](https://github.com/coinfoundry/miningcore/blob/master/README.md#windows).  Just copy the config file into the build directory.

```
Windows
windows-build.bat
Now copy config.json to ../../build, edit it to your liking and run:

cd ../../build
dotnet MiningCore.dll -c config.json
```

**Comment by hellomotow** [comment]
I missed the config file https://github.com/coinfoundry/miningcore/wiki/Configuration

**Comment by calvintam236** [comment]
The link you mentioned is just the guide how to configure. You should have config.json in the root folder, or look at the examples folder.

**Comment by actionTurtle** [comment]
I see the in the example folders there a quite a few different .json configs for different coins... if we want to allow people to mine different coins how do we combine the configs or is there just one folder we put all the productions ones in when we are ready to go?

Thanks!!!

**Comment by oliverw** [comment]
@actionTurtle You would just merge the the <code>pools</code> array of all of your configs into a single one.

**Comment by actionTurtle** [comment]
gotcha... so in production I would want to remove all the example folders and just have one single config.json file with all my coins and configs in there..

Kind of a side question and I know this is hard to answer because it depends on how many miners are on the pool. But what size VPS would you suggest would be needed to run the pools to start out? Is it actually very minimal services that you need because the mining is all happening on a user rig?

All the payout and user data and any data generated is stored in the postgreSQL database. How big can this database end up being? Say we had 5,000 active daily miners. How much data do you think we would generate in 30 days? A few MB's or a few GB's? Should I be prepared to have TB's of data in a few years?

Thank you!!!

**Comment by Kukks** [comment]
I would not worry about db size @actionTurtle  
I think your biggest resource hog will be the coin nodes. Depending on the coin, you should be prepared to host over 100Gb of blockchain data and require a few gbs of ram per node.

**Comment by oliverw** [comment]
@actionTurtle Coinfoundry's production DB is currently at 105 GB after 7 months of operation.

**Comment by actionTurtle** [comment]
Thanks @oliverw 

@Kukks that block chain data is stored in the DB correct? or is it somewhere else?

Thanks!!

**Comment by calvintam236** [comment]
@actionTurtle the blockchain data saved by the coin daemons.

**Comment by Kukks** [comment]
@actionTurtle No. It is saved separately per node.

**Comment by saltyminer** [comment]
@actionTurtle the blockchain data is stored on disk in a folder that is specified when setting up the coin daemon/wallet

**Comment by oliverw** [comment]
@actionTurtle Regarding your questions about recommended VM sizes. It may have gone out of style these days but Coinfoundry is running on real hardware instead of VMs. Our infrastructure is a bit over-provisioned since we are running 4 of [these](https://www.hetzner.com/dedicated-rootserver/ax60-ssd). One for all the Pool Stratums (Miningcore), two hosting all coin daemon nodes and one hosting the DB.

**Comment by actionTurtle** [comment]
Thank you everyone this is great info!!!

@saltyminer exactly what I needed... Thanks!!

**Comment by actionTurtle** [comment]
Lol... ok one last... but probably not question..

With read and write rates to the DB. @Oliver makes sense how you have broken it out... are read write rates really important to keep up so mining is effective? Like if I were to have a node in the US and Europe would I want to have a DB in both locations or would one in the US be fine for the node in Europe?

Thanks!!!

**Comment by oliverw** [comment]
@actionTurtle Interesting question. I'm currently trying to work out a strategy for that as well. Mining is extremely write-heavy on the DB. So write heavy that I'm currently facing a [performance problem](https://dba.stackexchange.com/questions/197502/postgresql-9-6-performance-problem-with-sum-aggregate-query) on Coinfoundry. I will update the Wiki once I've found a good strategy for global hosting.

**Comment by actionTurtle** [comment]
@oliverw sent you an email.... as this is so off topic for the location of the config file at this point... lol
