### ISSUE TITLE
Statistic issue 

### ISSUE THREAD

**Issue by itsmylife44** [coinfoundry/miningcore#278]
Hey , all right done with miningcore , and it's running :D

but on ste page , the statistic is

Network's Hash Rate
0 H/s

but in

Network Difficulty
3.23494 P

here is the json output : 

0 |  
-- | --
id | "eth1"
coin |  
type | "ETH"
algorithm | "Dagger-Hashimoto"
ports |  
3072 |  
listenAddress | "x.x.x.x"
difficulty | 0.1
varDiff |  
minDiff | 0.05
targetTime | 15
retargetTime | 90
variancePercent | 30
3073 |  
listenAddress | "x.x.x.x"
difficulty | 5000
paymentProcessing |  
enabled | true
minimumPayment | 0.01
payoutScheme | "PPLNS"
payoutSchemeConfig |  
factor | 2
minimumPaymentToPaymentId | 5
keepUncles | false
keepTransactionFees | false
clientConnectionTimeout | 600
jobRebroadcastTimeout | 0
blockRefreshInterval | 500
poolFeePercent | 0.65
address | "wallet"
addressInfoLink | "https://etherscan.io/address/wallet"
poolStats |  
connectedMiners | 0
poolHashrate | 0
validSharesPerSecond | 0
networkStats |  
networkHashrate | 0
networkDifficulty | 3293885025746226
lastNetworkBlockTime | "2018-03-21T21:34:46.240364"
blockHeight | 5297414
connectedPeers | 1
topMiners |  
0 |  
miner | "wallet"
hashrate | 298629739.7739987
sharesPerSecond | 0.18427676510598837
totalPaid | 0

you can see : networkHashrate | 0

**Comment by calvintam236** [comment]
Please use the issue template:

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state current commit hash.
Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by oliverw** [comment]
Network diff for Ethereum based chains is not available from the coin daemon itself. The only option is to fetch the value from external sources at the UI level.
