### ISSUE TITLE
API: Worker statistics question

### ISSUE THREAD

**Issue by be4i** [coinfoundry/miningcore#313]
Hello,
i was designing my front-end and i have seen a strange behavior (i think) in the results of the api. When i query the pool performance stats (/api/pools/id/performance) i am getting 25 samples for the last 24 hours (that's fine and normal behavior),but when query the worker stats (/api/id/worker/adddress/) i am getting 24 samples for the last 24 hours.And this makes a huge gap in the statistics i am showing (hour, hour and a half), i start digging in the source code and i found this:

https://github.com/coinfoundry/miningcore/blob/807490022c9de7b70321e70d69a282c66b523b78/src/MiningCore/Api/ApiServer.cs#L194-L195

and this:
https://github.com/coinfoundry/miningcore/blob/807490022c9de7b70321e70d69a282c66b523b78/src/MiningCore/Api/ApiServer.cs#L197-L198

this makes so the api is return only 23 hours of samples(because the hour and minutes are removed), what is the point?

**Comment by calvintam236** [comment]
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.
