### ISSUE TITLE
Effects Of Setting Smaller Window Factor: 2.0

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#326]
Currently test RVN pool and have so far hit two blocks. Both times just a very small fraction of total reward was paid out. Rest got stuck in a change address on the pool wallet. I think this is probably because the pool for testing is just around 300MH with 5-6 miners.

Note: This is using dev branch

Will changing:

`"factor": 2.0`

to something like

`"factor": 0.5`

Get payout amounts closer to where they should be? I am assuming it will payout the miners what's due but probably not all at once on the next block?

**Comment by Dradden** [comment]
I tried this out and dropped it to 0.5, and it has helped. payments are close. Here are the numbers of the two blocks hit since the change:

https://i.gyazo.com/085ac6d74282123335e1cd5ef71af819.png

I was hoping it would start paying out some of what is owed from the first two blocks that were hit at factor:2.0 but it hasn't really done that.

So what is the best way to adjust for that. Drop factor from 0.5 to lets say 0.3? Or would there be another method?

The live pool has 300+ miners and 12GH that will hit this pool when I forward them.

**Comment by gridmaniac** [comment]
We ran into the similar scenario.

Factor 2 actually means difficulty * 2.
The PPLNS algorithm is implemented exactly as described here: https://bitcointalk.org/index.php?topic=39832 (The correct method is as follows. - line)

So far we found three LTC blocks.

Our current window is about 1T shares (470G * 2 <- this factor).
So when we found first block we were having only ~380G shars, the rest part of window remained unpaid (36%) so we had to pay manually to our miners proportionally.

It is pointed in that post: "If the pool has just started, and a block is found before there are shares totaling a score of X, there will be leftover rewards and it should be decided what to do with them...Other options include donating to charity, or distributing among the miners."

After second block we had 100% shares paid out, but window is still quite large for us because of high amount of luck (avg 70%).

It is recommended to set X = 2, because (as I understand) average amount of shares for block is about 1 difficulty, then we add some variation value +0.5 and -0.5 so we get number 2.

We noticed that new miners are paid less on their first block mined with us, because window covers more than 1 block and it upsets our miners who are used to PPS.

We are planning to reduce X too, maybe we'll figure it out together.

**Comment by oliverw** [comment]
@gridmaniac You've explained it spot on. At Coinfoundry we also paid leftover funds for the first one or two blocks (depending on luck) by directly manipulating the balances table after using a spreadsheet to calculate the necessary changes. Later on all our pools have switched to window size 1.

**Comment by Dradden** [comment]
This is excellent information, thank you for sharing. I have a much more solid base understanding now. I will update here with any additional findings.

**Comment by structdjm** [comment]
can someone explain why networkdifficulty field in shares table isn't the same as the actual ravens network difficulty, its exponentially listed higher in the table, is this normal ?
