### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by structdjm** [coinfoundry/miningcore#361]
Noticed this error in console, was hoping someone could shed some light on it:

```console
[2018-06-14 22:52:46.7279] [E] [RVN] [Pool] [0HLEHVRF5OH7C] Connection json erro
r state: Unexpected character encountered while parsing value: :hearts:. Path '', line
0, position 0.
```

**Comment by calvintam236** [comment]
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by oliverw** [comment]
Someone who is most likely not a real miner is connecting to your stratum port. You can ignore this. Happens all the time.
