### ISSUE TITLE
Invalid solution: invalid collision length between StepRows

### ISSUE THREAD

**Issue by thisjrodriguez** [coinfoundry/miningcore#369]
Hi, there,

from time to time I see this error in the console (although it is not saved in the logs)

Invalid solution: invalid collision length between StepRows
X[i] = 08e9d4049dfrom0c83960271d404040860059ccc02b24b
X[i+1] = 0689c4069a8e048d700b7db20e92b9072e400374d4

I think he might be some kind of an ASIC. Any solutions? Or does that ring a bell?

zcashd (zclassic) {
  "version": 1001051,
  "protocolversion": 170002,
}
pool versión: 0.24

**Comment by calvintam236** [comment]
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by thisjrodriguez** [comment]
### **Description**
The console is not affected by an error, but it does not affect the mining pool.

Invalid solution: invalid collision length between StepRows
X[i] = 08e9d4049dfrom0c83960271d404040860059ccc02b24b
X[i+1] = 0689c4069a8e048d700b7db20e92b9072e400374d4

### **Steps to Reproduce**
you can't

### **Expected behavior**
I think he might be some kind of an ASIC. Any solutions? Or does that ring a bell?

### **Actual behavior**
Invalid solution: invalid collision length between StepRows
X[i] = 08e9d4049dfrom0c83960271d404040860059ccc02b24b
X[i+1] = 0689c4069a8e048d700b7db20e92b9072e400374d4

### **Reproduces how often**
every days

### **Version**
Zclassic version: 1001051,
Zclassic protocol version: 170002,
pool versión: 0.24
Ubuntu Xenial

### **Additional Information**

**Comment by osheen2241** [comment]
I've also experienced the same error on Zcash node

**Comment by zheng9980419** [comment]
I've also experienced the same error on Zcash node.Is the problem solved?

**Comment by oliverw** [comment]
Nope not solved yet. Working on it. No ETA.
