### ISSUE TITLE
Unable to convert suggested difficulty error displayed by miningcore

### ISSUE THREAD

**Issue by xborow** [coinfoundry/miningcore#380]
Hello, 

I run solo(for fun) bitcoin pool by using miningcore which is great with fronted in place now,  but yesterday i got unusual issue while renting 1P from miningrigrentals.com -attached as a picture

Had no issue before with any rigs rented from miningrigrentals

Any ideae why it happened or how to fix, please?
![sketch-1534843820912](https://user-images.githubusercontent.com/39295831/44393732-c6164c80-a535-11e8-8870-1d463420cc61.png)

**Comment by xborow** [comment]
@oliverw @calvintam236 any idea please? how to fix this?

**Comment by xborow** [comment]
Please if anybody can suggest a fix, i'll pay for it about 25e if working :)

**Comment by calvintam236** [comment]
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by xborow** [comment]
Description
Unable to convert suggested difficulty reported by miningcore while miner with 1Pentahesh connected

Steps to Reproduce
run miningcore
connect miner on port 4444 with difficulty set 1000000 var dif enabled: min. 1000000 max. 30000000
miner connected, issue imidiatelly reported by miningcore: unable to convert.. printscreen attached above

Expected behavior
Miner starts to share the shares

Actual behavior
the miner did not start sharing hashs, instead error unable to convert suggested dufficulty reported, printscreen attached above

Reproduces how often
each time when miner with 1Pentahash and more connected

Version
~/Downloads/miningcore$ cat .git/refs/heads/master
7207861cf09d8c2372a7a641883d0f35592f43d5
running linux ubuntu 16.04

Additional Information
no special settings, bitcoin deamon 0.16.2 and miningcore with port 4444 diff 1000000 var diff enabled min. 1000000 max. 30000000

**Comment by xborow** [comment]
Have reviewed the code of bitcoinpoolbase.cs and found out that miner can ask for higher diff, but can not ask for lower diff than the base one, i had set the base one to 1000000 and the miner asked for the diff 262000 which is lower than the base one, so my bad, @calvintam236 many thanks anyway
