### ISSUE TITLE
Question regarding backup daemons.

### ISSUE THREAD

**Issue by Bratan** [coinfoundry/miningcore#50]
I have a question regarding how the backup daemons work.

From what I can see, blocks are being submitted to all registered daemons but payments are being processed using only the first one in the list.

Won't this be a problem at some point, since blocks could be submitted to other daemons but payments will be processed only from the first daemon/wallet?

**Comment by oliverw** [comment]
Very legitimate question. Blocks are submitted to all daemons to get them included in the mainchain as fast and as reliable as possible. Double submissions would get rejected by the network. No problem for the pool. On the other hand payments cannot be submitted to multiple daemons as this would result in double or triple payouts - ruining the pool.

**Comment by Bratan-X** [comment]
Yes indeed, this is what I thought as well.

So this means that coins mined in the 2nd/3rd/etc. daemon/wallet need to be manually transferred to the first/main wallet in order for the payments to be processed?

**Comment by calvintam236** [comment]
@Bratan I think you can import the wallet using seeds or keys on the backup daemons so they have the same access of the same wallet?

**Comment by Bratan** [comment]
@calvintam236 - This is what I thought at first (cloning the wallet for multiple daemons), but it seems this is not supported and could/will run into problems. From what I understand the synchronization will only work up until some point.

https://bitcointalk.org/index.php?topic=1986.msg25154#msg25154

**Comment by oliverw** [comment]
@Bratan Thanks for the extremly helpful link. Looks like my assumption in this regard was to optimistic. 

Improvements to the daemon interface are already on top of my todo list after improvements to the REST API. Since running multiple wallet copies is not a supported scenario one of the changes I'm planning to extend the [tagging mechanism used for the Monero wallet daemon](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Monero/MoneroJobManager.cs#L289) to all currencies. That way the pool would continue to function even if the wallet daemon goes down which would just result in delayed payouts.

I'm planning to augment this with new functionality in the DaemonInterface class that will continously monitor all attached daemons, take unhealthy ones out of request processing and notify the admin about the outage.

**Comment by calvintam236** [comment]
@Bratan how about using same blockchain (same data folder) by multiple daemons? i think this might make more sense, and it is supported

https://monero.stackexchange.com/questions/3689/why-would-you-need-multiple-daemons-using-one-lmdb-database

**Comment by Serpent6877** [comment]
I have been running redundant Parity daemons for a couple months without issues. Using the same wallet address. They are running on two separate machines. It is how I handle east/west coast configurations. They then peer with each other.
