### ISSUE TITLE
Best practice to start a mining pool using miningcore

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#524]
Hi,
Sorry for open a not real issue, but I couldn't find any better place to post this.

I am planning to start a mining pool for the following coins using miningcore: ETH, ETC, RVN, BTG, XMR, BCD, ZCASH, BTC.

Now I want to know is it better if I get a very powerful server and run all the daemons and miningcore in one server or is it better if I get a VPS per coin in the same data center to run the daemon, or is it better to get a separate VPS for coins like ETH and BTC and get a server to host the rest and the miningcore app? and what is your suggested config for each scenario?

Thanks

**Comment by calebcall** [comment]
I won't say which is better (I don't think there's necessarily a correct answer to this), but will rather point out some things to consider.  The coins you selected are all popular coins and have decent sized chains.  For example, BCD alone is 155G.  I don't know for sure (since I don't run them) but I'm sure BTC, ETH, and probably XMR all have chains much larger than that.  So, a single server will need to have decent sized disks to run them all on one.  Some other things to consider is if your pool becomes popular, how do you plan to scale?  If you cram it all on a single server, you're going to have to figure out how to break it all apart when you need to scale it out.  There's several ways it can be scaled, I personally keep every piece (UI, api, database, stratum, etc) as separate as possible and can scale each piece as needed.  Good luck with your pool!

**Comment by peysab** [comment]
Thank you, now I have a better insight of what I should do.
